version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate  && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:


