# Generated by Django 4.1.5 on 2023-01-08 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, help_text='Укажите дату в формате "DD.MM.YYYY или YYYY-MM-DD" ', null=True, verbose_name='Дата создания')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Телефон передается в стандартном формате \n                                           +7|7|8 xxx xxx xx xx (X - от 0 до 10)', regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')], verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Почта неверного формата', regex='^[-\\w\\.]+@([-\\w]+\\.)+[-\\w]{2,4}$')], verbose_name='Почта')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
    ]
