# Generated by Django 4.1.5 on 2023-01-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(help_text='Укажите дату в формате "DD.MM.YYYY или YYYY-MM-DD" ', verbose_name='Дата создания'),
        ),
    ]
