# Generated by Django 4.1.5 on 2023-01-06 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mymodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Укажите дату в формате "DD.MM.YYYY или YYYY-MM-DD" ', null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон передается в стандартном формате \n                                           +7|7|8 xxx xxx xx xx (X - от 0 до 10)', regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
