# Generated by Django 4.1.5 on 2023-01-06 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mymodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Почта неверного формата', regex='^[-\\w\\.]+@([-\\w]+\\.)+[-\\w]{2,4}$')], verbose_name='Почта'),
        ),
    ]
