# Generated by Django 4.1.5 on 2023-01-06 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mymodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Почта неверного формата', regex='^[-\\w\\.]+@([-\\w]+\\.)+[-\\w]{2,4}$')], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Телефон передается в стандартном формате \n                                           +7|7|8 xxx xxx xx xx (X - от 0 до 10)', regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')], verbose_name='Номер телефона'),
        ),
    ]
